### ISSUE TITLE
无法获准确获取当前播放视频

### ISSUE THREAD

**Issue by billowssun** [xuncv/WeChatDownloader#3]

**Comment by 467815891a** [comment]
打开WeChatDownloader，打开视频，关闭视频，打开视频，关闭视频，打开视频，获取地址，下载视频

**Comment by xuncv** [comment]
微信视频号升级了，内容丰富了，导致内存搜索命中率低。可以试试我另一种实现方式，https://github.com/xuncv/WechatVideoSniffer
