### ISSUE TITLE
围观沙雕 @longlivenazi ，原标题：注意，這不是開源軟體，下載後windenfender報毒

### ISSUE THREAD

**Issue by longlivenazi** [xuncv/WeChatDownloader#4]

**Comment by xuncv** [comment]
给你一个大比兜！

**Comment by OCFsummer** [comment]
应该是内存扫描导致报警了，目前测试挺好用的

**Comment by longlivenazi** [comment]
> 应该是内存扫描导致报警了，目前测试挺好用的

這就是個假開源的軟體，指不定有多少後門

**Comment by xuncv** [comment]
@longlivenazi  你他妈的是个大沙雕吧，满打满算58行代码，还尼玛指不定多少后门。把你挂起来供github围观

**Comment by longlivenazi** [comment]
哈哈哈，不會吧不會吧，這就急了？講這些沒用的~有能耐真開源吼，挂著吧，正好讓其他人看看這假開源😏

**Comment by xuncv** [comment]
来吧 臭傻逼，举证吧。如何证明这不是开源软件？

**Comment by longlivenazi** [comment]
首先吼，我不是計算機相關人員，只是層經看過哪個主播講過，GitHub開源軟體可以在action裏面編譯出執行文件，我fork你的代碼編譯不出來唔🤔

**Comment by Frank0427** [comment]
确实有杀毒软件误报的问题，这是正常的，因为软件的发布已经有一些约定俗成的工业标准，一般开源软件爱好者没有精力去顾及这些，开放源码让大家自己去编译就已经是最好的诚意。编译不出来，那就是自己的问题，一般有点动手能力的也不至于凡事都要捡现成的。作者开放exe给大家下载就已经是帮忙了，懂的就用。
我是McAfee报病毒，还不让找回来，作者用的这个语言我也不会，所以我放弃了，用了别的方案。
但还是要专门挺作者一波，这真的不是他的问题。大家和平交流吧，毕竟来github的人，都有共同的兴趣爱好。

**Comment by qeqeq1** [comment]
> 首先吼，我不是計算機相關人員，只是層經看過哪個主播講過，GitHub開源軟體可以在action裏面編譯出執行文件，我fork你的代碼編譯不出來唔🤔

首先我不懂代码
其次我编译不出来
再其次杀毒软件报毒
所以这个软件是病毒
笑死了

**Comment by longlivenazi** [comment]
不是計算機相關人員就不懂代碼？就你懂？笑死了~

**Comment by longlivenazi** [comment]
> > 首先吼，我不是計算機相關人員，只是層經看過哪個主播講過，GitHub開源軟體可以在action裏面編譯出執行文件，我fork你的代碼編譯不出來唔🤔
> 
> 首先我不懂代码 其次我编译不出来 再其次杀毒软件报毒 所以这个软件是病毒 笑死了


不是計算機相關人員就不懂代碼？就你懂？笑死了~

**Comment by qeqeq1** [comment]
> > > 首先吼，我不是計算機相關人員，只是層經看過哪個主播講過，GitHub開源軟體可以在action裏面編譯出執行文件，我fork你的代碼編譯不出來唔🤔
> > 
> > 
> > 首先我不懂代码 其次我编译不出来 再其次杀毒软件报毒 所以这个软件是病毒 笑死了
> 
> 不是計算機相關人員就不懂代碼？就你懂？笑死了~

既然你就说说有什么后门啊，远程执行还是如何如何

**Comment by longlivenazi** [comment]
> > 首先吼，我不是計算機相關人員，只是層經看過哪個主播講過，GitHub開源軟體可以在action裏面編譯出執行文件，我fork你的代碼編譯不出來唔🤔
> 
> 首先我不懂代码 其次我编译不出来 再其次杀毒软件报毒 所以这个软件是病毒 笑死了

沒長眼睛建議回爐重造唔，我只是對開源此軟體開源真實性存在疑問，報毒也是事實，我沒有跟你個只拿一樣信誓旦旦唔😏

**Comment by longlivenazi** [comment]
> > > > 首先吼，我不是計算機相關人員，只是層經看過哪個主播講過，GitHub開源軟體可以在action裏面編譯出執行文件，我fork你的代碼編譯不出來唔🤔
> > > 
> > > 
> > > 首先我不懂代码 其次我编译不出来 再其次杀毒软件报毒 所以这个软件是病毒 笑死了
> > 
> > 
> > 不是計算機相關人員就不懂代碼？就你懂？笑死了~
> 
> 既然你就说说有什么后门啊，远程执行还是如何如何

想學啊？交學費唔~😁
